version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        ports:
            - "9000:9000"
        networks:
            - laravel
        depends_on:
            - postgres
        environment:
            - APP_ENV=local
            - DB_CONNECTION=pgsql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret

    web:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    postgres:
        image: postgres:15
        container_name: laravel_postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

    node:
        image: node:18-alpine
        container_name: laravel_node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "5173:5173"
        command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
        networks:
            - laravel

volumes:
    pgdata:

networks:
    laravel:
        driver: bridge
