version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        ports:
            - "9000:9000"
        networks:
            - laravel
        depends_on:
            - postgres
        environment:
            - APP_ENV=production
            - DB_CONNECTION=pgsql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret

    postgres:
        image: postgres:15
        container_name: laravel_postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

    caddy:
      image: caddy:2
      container_name: caddy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - .:/var/www/html
        - caddy_data:/data
        - caddy_config:/config
      depends_on:
        - app
      networks:
        - laravel

volumes:
    pgdata:
    caddy_data:
    caddy_config:

networks:
    laravel:
        driver: bridge
